### ISSUE TITLE
How to set TRACK_MOVIES when using custom application.yaml

### ISSUE THREAD

**Issue by friimaind** [Zggis/plex-tvtime#22]
I'm using Plex TvTime under Unraid and I have two users under sync.
I'm using a custom yaml file, all works fine.

```
account-config:
  accounts:
    #Add any number of TVTime accounts below
    #To use an environment variable as the value use ${YOUR_ENVIRONMENT_VARIABLE}
    #Make sure the '-' is on a line of its own
    -
      tvtimeUser: user1
      tvtimePassword: pwd1
      plexUsers: plexuser1
    -
      tvtimeUser: user2
      tvtimePassword: pwd2
      plexUsers: plexuser2

logging:
  level:
    com:
      zggis: ${LOGGING_LEVEL:INFO}
```

if I understand correctly the custom yaml file overwrites the docker container configurations so, in the screenshot, TRACK_MOVIES will be ignored, right?

![image](https://github.com/user-attachments/assets/c282543f-676f-4299-b160-07f9670dc57c)

Where do I set TRACK_MOVIES in the yaml file?

Thank you!
